### ISSUE TITLE
defrost CML cannot be planted

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#113]
Defrost day shows 0day, but missing Action item

![image](https://user-images.githubusercontent.com/12605218/126571747-0ed814c6-9afb-44b4-86d3-d4f7436ce0a3.png)

![image](https://user-images.githubusercontent.com/12605218/126571865-87312efc-d95b-40f0-87eb-7f410f2f34bd.png)

**Comment by liyangwood** [comment]
fixed. 
Can test after deployed with wallet version 0.0.10

**Comment by kevingzhang** [comment]
still shows defrost 0day without plant action in version 0.0.13

**Comment by liyangwood** [comment]
cml id?

**Comment by lxm218** [comment]
current version is 0.0.14
![image](https://user-images.githubusercontent.com/12605218/127698000-a2a88d94-b73c-4475-82ce-4588892049b9.png)
