### ISSUE TITLE
Delete auction - change dialog text

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#200]
For delete auction by owner, change the current wording:

<img width="1115" alt="Screen Shot 2021-08-23 at 7 30 39 AM" src="https://user-images.githubusercontent.com/86096370/130471408-d2404ecb-c0d1-47e7-8d4f-8b02491a5687.png">

Change to:

**Removing this auction will charge you 1 TEA. Are you sure?**

**Comment by liyangwood** [comment]
done in test-net
wallet version T_0.1.61

**Comment by kevingzhang** [comment]
Note to @geopor , the T_0.xxx version is not the one deployed to wallet.teaproject.org. This is for internal test and will be in our next epoch.

You can try the test net by clicking http://139.198.27.87/#/home

Please bookmark this address. All our new issues tests happen here.

**Comment by geopor** [comment]
Ok testnet address noted.

Right now there is still an error in the wording. It should read as follows:

> Remov**ing** this auction will charge you 1 TEA. Are you sure?

Note that it's **Removing** and that there is a period after **TEA** instead of a comma.

**Comment by geopor** [comment]
The modal in the above comment is if there is an active bid. 
We should also change the wording on the modal dialog when the seller tries to delete the auction with no active bids.

<img width="1167" alt="Screen Shot 2021-08-24 at 10 06 00 AM" src="https://user-images.githubusercontent.com/86096370/130660638-2ed73cd0-1583-4811-ba46-a3dbba1dd0a6.png">

should be changed to:

> Are you sure you want to delete this auction?

**Comment by liyangwood** [comment]
done in test-net
wallet version T_0.1.68

**Comment by geopor** [comment]
<img width="479" alt="Screen Shot 2021-08-24 at 11 34 01 PM" src="https://user-images.githubusercontent.com/86096370/130738565-7142e9ab-2456-4a72-9c41-48aa58768fca.png">

There is still a comma between sentences. It should be a period.

**Comment by liyangwood** [comment]
fixed in test-net
